# Limitless/Milight platform.
- platform: limitlessled
  bridges:
    - host: !secret light_milighthub_host
      port: !secret light_milighthub_port
      version: 6
      groups:
      - number: 1
        name: milight_shed_garden
        type: rgbww
        fade: off

# Limitless/Milight platform based on mqtt_json
- platform: mqtt
  schema: json
  name: milight_shed_garden_mqtt
  state_topic: "/milight/states/0x173D/rgb_cct/1"
  command_topic: "/milight/commands/0x173D/rgb_cct/1"
  brightness: true
  color_temp: true
  effect: true
  #Effect list 0=Full, 1=White, 2=RGB, 3=Full hard, 4=Disco, 5=Red Flash, 6=Green Flash, 7=Blue Flash, 8=White Flash]
  effect_list: [0, 1, 2, 3, 4 ,5, 6, 7, 8]
  rgb: true
  optimistic: false
  retain: true
  qos: 0

# Template light hall.
# Based upon Fibaro switch and IKEA Tradfri lights.
- platform: template
  lights:
    light_hall:
      friendly_name: Lamp Hal
      entity_id:
        - switch.fibaro_hall_light_switch_2
        - light.lamp_hal
      value_template: >-
        {% if is_state('switch.fibaro_hall_light_switch_2', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      level_template: "{{ states.light.lamp_hal.attributes.brightness|int }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.fibaro_hall_light_switch_2
      turn_off:
        service: switch.turn_off
        entity_id: switch.fibaro_hall_light_switch_2
      set_level:
        service: light.turn_on
        data_template:
          entity_id: light.lamp_hal
          brightness: "{{ brightness }}"

# Template light corridor.
# Based upon Fibaro switch and IKEA Tradfri lights.
- platform: template
  lights:
    light_corridor:
      friendly_name: Lamp Overloop (Boven)
      entity_id:
        - switch.fibaro_corridor_light_switch
        - light.lamp_overloop
      value_template: >-
        {% if is_state('switch.fibaro_corridor_light_switch', 'on') %}
          on
        {% else %}
          off
        {% endif %}
      level_template: "{{ states.light.lamp_overloop.attributes.brightness|int }}"
      turn_on:
        service: switch.turn_on
        entity_id: switch.fibaro_corridor_light_switch
      turn_off:
        service: switch.turn_off
        entity_id: switch.fibaro_corridor_light_switch
      set_level:
        service: light.turn_on
        data_template:
          entity_id: light.lamp_overloop
          brightness: "{{ brightness }}"
